/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.1.9-dev at Thu Jun  6 18:31:35 2013. */

#include "basestation.pb.h"



const pb_field_t basestation_Out_fields[6] = {
    {3, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    offsetof(basestation_Out, batteryLevel),
    pb_delta(basestation_Out, has_batteryLevel, batteryLevel),
    pb_membersize(basestation_Out, batteryLevel), 0, 0},

    {4, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_Out, packetLoss, batteryLevel),
    pb_delta(basestation_Out, has_packetLoss, packetLoss),
    pb_membersize(basestation_Out, packetLoss), 0, 0},

    {5, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_Out, temperature, packetLoss),
    pb_delta(basestation_Out, has_temperature, temperature),
    pb_membersize(basestation_Out, temperature), 0, 0},

    {6, (pb_type_t) ((int) PB_HTYPE_CALLBACK | (int) PB_LTYPE_SUBMESSAGE),
    pb_delta_end(basestation_Out, topology, temperature), 0,
    pb_membersize(basestation_Out, topology), 0,
    &basestation_Out_Topology_fields},

    {7, (pb_type_t) ((int) PB_HTYPE_CALLBACK | (int) PB_LTYPE_SUBMESSAGE),
    pb_delta_end(basestation_Out, node, topology), 0,
    pb_membersize(basestation_Out, node), 0,
    &basestation_Out_Node_fields},

    PB_LAST_FIELD
};

const pb_field_t basestation_Out_Topology_fields[3] = {
    {1, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    offsetof(basestation_Out_Topology, destinationId), 0,
    pb_membersize(basestation_Out_Topology, destinationId), 0, 0},

    {2, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_Out_Topology, previousId, destinationId), 0,
    pb_membersize(basestation_Out_Topology, previousId), 0, 0},

    PB_LAST_FIELD
};

const pb_field_t basestation_Out_Node_fields[4] = {
    {1, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    offsetof(basestation_Out_Node, nodeId), 0,
    pb_membersize(basestation_Out_Node, nodeId), 0, 0},

    {2, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_Out_Node, deviceId, nodeId), 0,
    pb_membersize(basestation_Out_Node, deviceId), 0, 0},

    {3, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_Out_Node, deviceType, deviceId),
    pb_delta(basestation_Out_Node, has_deviceType, deviceType),
    pb_membersize(basestation_Out_Node, deviceType), 0, 0},

    PB_LAST_FIELD
};

const pb_field_t basestation_In_fields[5] = {
    {1, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    offsetof(basestation_In, time),
    pb_delta(basestation_In, has_time, time),
    pb_membersize(basestation_In, time), 0, 0},

    {2, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_In, networkId, time),
    pb_delta(basestation_In, has_networkId, networkId),
    pb_membersize(basestation_In, networkId), 0, 0},

    {3, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_In, lastTransferSize, networkId),
    pb_delta(basestation_In, has_lastTransferSize, lastTransferSize),
    pb_membersize(basestation_In, lastTransferSize), 0, 0},

    {4, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(basestation_In, transferInterval, lastTransferSize),
    pb_delta(basestation_In, has_transferInterval, transferInterval),
    pb_membersize(basestation_In, transferInterval), 0, 0},

    PB_LAST_FIELD
};

